In [2]:
# Importing our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Importing and read the charity_data.csv.
import pandas as pd 
heart_disease_df = pd.read_csv("Resources/heart_2022_no_nans.csv")
heart_disease_df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,...,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,...,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,...,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,...,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,...,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [3]:
# Dropping the non-beneficial ID columns, 'PhysicalHealthDays', 'MentalHealthDays', 'LastCheckupTime', 'SmokerStatus', and 'ECigaretteUsage'.
heart_disease_df.drop(['PhysicalHealthDays', 'MentalHealthDays', 'LastCheckupTime', 'SmokerStatus', 'ECigaretteUsage'], axis=1, inplace=True)
heart_disease_df.head(3)

,State,Sex,GeneralHealth,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,Yes,9.0,None of them,No,No,No,No,...,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,Yes,6.0,None of them,No,No,No,No,...,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,No,8.0,"6 or more, but not all",No,No,No,No,...,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes

In [4]:
heart_disease_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 35 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      246022 non-null  object
 1   Sex                        246022 non-null  object
 2   GeneralHealth              246022 non-null  object
 3   PhysicalActivities         246022 non-null  object
 4   SleepHours                 246022 non-null  float64
 5   RemovedTeeth               246022 non-null  object
 6   HadHeartAttack             246022 non-null  object
 7   HadAngina                  246022 non-null  object
 8   HadStroke                  246022 non-null  object
 9   HadAsthma                  246022 non-null  object
 10  HadSkinCancer              246022 non-null  object
 11  HadCOPD                    246022 non-null  object
 12  HadDepressiveDisorder      246022 non-null  object
 13  HadKidneyDisease           246022 non-null  object
 14  HadArthritis               246022 non-null  object
 15  HadDiabetes                246022 non-null  object
 16  DeafOrHardOfHearing        246022 non-null  object
 17  BlindOrVisionDifficulty    246022 non-null  object
 18  DifficultyConcentrating    246022 non-null  object
 19  DifficultyWalking          246022 non-null  object
 20  DifficultyDressingBathing  246022 non-null  object
 21  DifficultyErrands          246022 non-null  object
 22  ChestScan                  246022 non-null  object
 23  RaceEthnicityCategory      246022 non-null  object
 24  AgeCategory                246022 non-null  object
 25  HeightInMeters             246022 non-null  float64
 26  WeightInKilograms          246022 non-null  float64
 27  BMI                        246022 non-null  float64
 28  AlcoholDrinkers            246022 non-null  object
 29  HIVTesting                 246022 non-null  object
 30  FluVaxLast12               246022 non-null  object
 31  PneumoVaxEver              246022 non-null  object
 32  TetanusLast10Tdap          246022 non-null  object
 33  HighRiskLastYear           246022 non-null  object
 34  CovidPos                   246022 non-null  object
dtypes: float64(4), object(31)
memory usage: 65.7+ MB

In [5]:
# Dropping additional non-beneficial columns, 'HadDepressiveDisorder', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty', 'DifficultyConcentrating', 'DifficultyWalking', 'DifficultyDressingBathing', and 'DifficultyErrands'
heart_disease_df.drop(['HadDepressiveDisorder', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty', 'DifficultyConcentrating', 'DifficultyWalking', 'DifficultyDressingBathing', 'DifficultyErrands'], axis=1, inplace=True)

heart_disease_df.head(3)

,State,Sex,GeneralHealth,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,Yes,9.0,None of them,No,No,No,No,...,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,Yes,6.0,None of them,No,No,No,No,...,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,No,8.0,"6 or more, but not all",No,No,No,No,...,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes

In [6]:
heart_disease_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 28 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   State                  246022 non-null  object
 1   Sex                    246022 non-null  object
 2   GeneralHealth          246022 non-null  object
 3   PhysicalActivities     246022 non-null  object
 4   SleepHours             246022 non-null  float64
 5   RemovedTeeth           246022 non-null  object
 6   HadHeartAttack         246022 non-null  object
 7   HadAngina              246022 non-null  object
 8   HadStroke              246022 non-null  object
 9   HadAsthma              246022 non-null  object
 10  HadSkinCancer          246022 non-null  object
 11  HadCOPD                246022 non-null  object
 12  HadKidneyDisease       246022 non-null  object
 13  HadArthritis           246022 non-null  object
 14  HadDiabetes            246022 non-null  object
 15  ChestScan              246022 non-null  object
 16  RaceEthnicityCategory  246022 non-null  object
 17  AgeCategory            246022 non-null  object
 18  HeightInMeters         246022 non-null  float64
 19  WeightInKilograms      246022 non-null  float64
 20  BMI                    246022 non-null  float64
 21  AlcoholDrinkers        246022 non-null  object
 22  HIVTesting             246022 non-null  object
 23  FluVaxLast12           246022 non-null  object
 24  PneumoVaxEver          246022 non-null  object
 25  TetanusLast10Tdap      246022 non-null  object
 26  HighRiskLastYear       246022 non-null  object
 27  CovidPos               246022 non-null  object
dtypes: float64(4), object(24)
memory usage: 52.6+ MB

In [10]:
# Replacing "Yes" with 1 and "No" with 0 in the specified columns
columns_to_replace = ['HadHeartAttack', 'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer',
                      'HadCOPD', 'HadKidneyDisease', 'HadArthritis', 'HadDiabetes', 'ChestScan',
                      'AlcoholDrinkers', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver',
                      'TetanusLast10Tdap', 'HighRiskLastYear', 'CovidPos']

# Replacing specified columns in the DataFrame
heart_disease_df[columns_to_replace] = heart_disease_df[columns_to_replace].replace({'Yes': 1, 'No': 0})

# Showing the DataFrame with replaced values
heart_disease_df.head()

,State,Sex,GeneralHealth,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,Yes,9.0,None of them,0,0,0,0,...,1.60,71.67,27.99,0,0,1,1,"Yes, received Tdap",0,0
1,Alabama,Male,Very good,Yes,6.0,None of them,0,0,0,0,...,1.78,95.25,30.13,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,Alabama,Male,Very good,No,8.0,"6 or more, but not all",0,0,0,0,...,1.85,108.86,31.66,1,0,0,1,"No, did not receive any tetanus shot in the pa...",0,1
3,Alabama,Female,Fair,Yes,9.0,None of them,0,0,0,0,...,1.70,90.72,31.32,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,1
4,Alabama,Female,Good,Yes,5.0,1 to 5,0,0,0,0,...,1.55,79.38,33.07,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,0

In [11]:
# Determining the number of unique values in each column.
unique_values_in_each_column = heart_disease_df.nunique()
unique_values_in_each_column

State                      54
Sex                         2
GeneralHealth               5
PhysicalActivities          2
SleepHours                 23
RemovedTeeth                4
HadHeartAttack              2
HadAngina                   2
HadStroke                   2
HadAsthma                   2
HadSkinCancer               2
HadCOPD                     2
HadKidneyDisease            2
HadArthritis                2
HadDiabetes                 4
ChestScan                   2
RaceEthnicityCategory       5
AgeCategory                13
HeightInMeters            101
WeightInKilograms         516
BMI                      3514
AlcoholDrinkers             2
HIVTesting                  2
FluVaxLast12                2
PneumoVaxEver               2
TetanusLast10Tdap           4
HighRiskLastYear            2
CovidPos                    3
dtype: int64

In [12]:
# Looking at 'BMI' value counts for binning
bmi_value_counts = heart_disease_df['BMI'].value_counts()
bmi_value_counts

BMI
26.63    2727
27.46    2040
27.44    1964
24.41    1922
27.12    1893
         ...
41.65       1
33.24       1
25.57       1
13.64       1
45.28       1
Name: count, Length: 3514, dtype: int64

In [17]:
# Looking for 'BMI" value counts greater than 100
bmi_value_counts[bmi_value_counts>100]

BMI
26.63    2727
27.46    2040
27.44    1964
24.41    1922
27.12    1893
         ...
23.87     102
22.13     102
29.37     102
19.79     101
24.83     101
Name: count, Length: 511, dtype: int64

In [19]:
# Determining which values can be replaced if counts are less than or equal to 100.
names_to_replace = list(bmi_value_counts[bmi_value_counts <= 100].index)

# Replacing values in the DataFrame
for name in names_to_replace:
    heart_disease_df['BMI'] = heart_disease_df['BMI'].replace(name, 'Other')
    
# Checking to make sure the binning process was successful
heart_disease_df['BMI'].value_counts()

BMI
Other    49211
26.63     2727
27.46     2040
27.44     1964
24.41     1922
         ...
29.37      102
22.13      102
23.87      102
19.79      101
24.83      101
Name: count, Length: 512, dtype: int64

In [20]:
# Looking at 'State' value counts for binning
state_value_counts = heart_disease_df['State'].value_counts()
state_value_counts

State
Washington              15000
Maryland                 9165
Minnesota                9161
Ohio                     8995
New York                 8923
Texas                    7408
Florida                  7315
Kansas                   6145
Wisconsin                6126
Maine                    6013
Iowa                     5672
Hawaii                   5596
Virginia                 5565
Indiana                  5502
South Carolina           5471
Massachusetts            5465
Arizona                  5462
Utah                     5373
Michigan                 5370
Colorado                 5159
Nebraska                 5107
California               5096
Connecticut              5053
Georgia                  4978
Vermont                  4845
South Dakota             4405
Montana                  4264
Missouri                 4195
New Jersey               3967
New Hampshire            3756
Puerto Rico              3589
Idaho                    3468
Alaska                   3205
Rhode Island             3112
Oregon                   3049
Louisiana                3010
West Virginia            2974
New Mexico               2968
Oklahoma                 2941
Arkansas                 2940
Pennsylvania             2729
Tennessee                2725
Illinois                 2607
North Carolina           2551
North Dakota             2498
Mississippi              2438
Kentucky                 2413
Wyoming                  2410
Delaware                 2155
Alabama                  1902
Nevada                   1769
District of Columbia     1725
Guam                     1549
Virgin Islands            743
Name: count, dtype: int64

In [23]:
# Choose a cutoff value and create a list of state values to be replaced

# Choosing a cutoff value for the number of occurrences
cutoff_value = 5000 

# Creating a list of state value types to be replaced
states_to_replace = state_value_counts[state_value_counts < cutoff_value].index.tolist()

# Replacing in DataFrame
for app in states_to_replace:
    heart_disease_df['State'] = heart_disease_df['State'].replace(app,"Other")

# Checking to make sure binning was successful
heart_disease_df['State'].value_counts()

State
Other             91880
Washington        15000
Maryland           9165
Minnesota          9161
Ohio               8995
New York           8923
Texas              7408
Florida            7315
Kansas             6145
Wisconsin          6126
Maine              6013
Iowa               5672
Hawaii             5596
Virginia           5565
Indiana            5502
South Carolina     5471
Massachusetts      5465
Arizona            5462
Utah               5373
Michigan           5370
Colorado           5159
Nebraska           5107
California         5096
Connecticut        5053
Name: count, dtype: int64

In [22]:
# Looking at 'WeightInKilograms' value counts for binning
weight_in_kilograms_value_counts = heart_disease_df['WeightInKilograms'].value_counts()
weight_in_kilograms_value_counts

WeightInKilograms
90.72     13066
81.65     12018
68.04     10365
72.57     10350
77.11      9725
          ...
238.14        1
200.49        1
166.47        1
205.02        1
30.39         1
Name: count, Length: 516, dtype: int64

In [24]:
# Choose a cutoff value and create a list of WeightInKilograms to be replaced

# Choosing a cutoff value for the number of occurrences
cutoff_value = 5000  

# Create a list of WeightInKilograms to be replaced
classifications_to_replace = weight_in_kilograms_value_counts[weight_in_kilograms_value_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    heart_disease_df['WeightInKilograms'] = heart_disease_df['WeightInKilograms'].replace(cls,"Other")
    
# Check to make sure binning was successful
heart_disease_df['WeightInKilograms'].value_counts()

WeightInKilograms
Other     119837
90.72      13066
81.65      12018
68.04      10365
72.57      10350
77.11       9725
86.18       8808
63.5        7570
79.38       7229
99.79       6818
74.84       6593
83.91       6475
95.25       6065
58.97       5721
104.33      5187
65.77       5185
70.31       5010
Name: count, dtype: int64

In [25]:
# Generating an array of the DataFrames categorical variables
categorical_variables = list(heart_disease_df.dtypes[heart_disease_df.dtypes == 'object'].index)
categorical_variables

['State',
 'Sex',
 'GeneralHealth',
 'PhysicalActivities',
 'RemovedTeeth',
 'HadDiabetes',
 'RaceEthnicityCategory',
 'AgeCategory',
 'WeightInKilograms',
 'BMI',
 'TetanusLast10Tdap',
 'CovidPos']

In [26]:
# Convert categorical data to numeric with `pd.get_dummies`
new_heart_disease_df = pd.get_dummies(heart_disease_df)

# Displaying the first few rows of the updated DataFrame
new_heart_disease_df.head()

,SleepHours,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadKidneyDisease,HadArthritis,ChestScan,...,BMI_46.99,BMI_48.42,BMI_Other,"TetanusLast10Tdap_No, did not receive any tetanus shot in the past 10 years","TetanusLast10Tdap_Yes, received Tdap","TetanusLast10Tdap_Yes, received tetanus shot but not sure what type","TetanusLast10Tdap_Yes, received tetanus shot, but not Tdap",CovidPos_0,CovidPos_1,CovidPos_Tested positive using home test without a health professional
0,9.0,0,0,0,0,0,0,0,1,0,...,False,False,False,False,True,False,False,True,False,False
1,6.0,0,0,0,0,0,0,0,1,0,...,False,False,False,False,False,True,False,True,False,False
2,8.0,0,0,0,0,0,0,0,1,1,...,False,False,False,True,False,False,False,False,True,False
3,9.0,0,0,0,0,1,0,0,1,0,...,False,False,False,True,False,False,False,False,True,False
4,5.0,0,0,0,0,0,0,0,1,0,...,False,False,False,True,False,False,False,True,False,False

In [49]:
# Split our preprocessed data into our features and target arrays
y = new_heart_disease_df['HadHeartAttack'].values
X = new_heart_disease_df.drop(columns=['HadHeartAttack']).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [50]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [51]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

# Defining the deep neural net model
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  100
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 10

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

c:\Users\larry\anaconda3\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 100)            │        61,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 30)             │         3,030 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 10)             │           310 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64,451 (251.76 KB)

 Trainable params: 64,451 (251.76 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
# Compiling the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
# Training the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.9459 - loss: 0.1831
Epoch 2/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9480 - loss: 0.1452
Epoch 3/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9515 - loss: 0.1395
Epoch 4/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9512 - loss: 0.1386
Epoch 5/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9532 - loss: 0.1344
Epoch 6/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9544 - loss: 0.1327
Epoch 7/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9565 - loss: 0.1274
Epoch 8/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9578 - loss: 0.1241
Epoch 9/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9596 - loss: 0.1192
Epoch 10/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9615 - loss: 0.1143
Epoch 11/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9621 - loss: 0.1115
Epoch 12/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9648 - loss: 0.1047
Epoch 13/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9647 - loss: 0.1042
Epoch 14/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9665 - loss: 0.0985
Epoch 15/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9675 - loss: 0.0962
Epoch 16/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9687 - loss: 0.0937
Epoch 17/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9706 - loss: 0.0891
Epoch 18/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9705 - loss: 0.0873
Epoch 19/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9723 - loss: 0.0837
Epoch 20/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9733 - loss: 0.0807
Epoch 21/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9735 - loss: 0.0800
Epoch 22/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9749 - loss: 0.0756
Epoch 23/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9742 - loss: 0.0765
Epoch 24/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9754 - loss: 0.0746
Epoch 25/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9759 - loss: 0.0726
Epoch 26/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9764 - loss: 0.0718
Epoch 27/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9766 - loss: 0.0705
Epoch 28/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9772 - loss: 0.0694
Epoch 29/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9780 - loss: 0.0684
Epoch 30/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9779 - loss: 0.0658
Epoch 31/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9782 - loss: 0.0662
Epoch 32/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9787 - loss: 0.0640
Epoch 33/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9793 - loss: 0.0627
Epoch 34/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9790 - loss: 0.0632
Epoch 35/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9794 - loss: 0.0629
Epoch 36/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9804 - loss: 0.0610
Epoch 37/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9802 - loss: 0.0617
Epoch 38/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9805 - loss: 0.0591
Epoch 39/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9810 - loss: 0.0592
Epoch 40/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9812 - loss: 0.0585
Epoch 41/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9810 - loss: 0.0584
Epoch 42/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9816 - loss: 0.0572
Epoch 43/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9810 - loss: 0.0589
Epoch 44/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9816 - loss: 0.0558
Epoch 45/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9816 - loss: 0.0558
Epoch 46/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9820 - loss: 0.0554
Epoch 47/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9822 - loss: 0.0552
Epoch 48/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9827 - loss: 0.0539
Epoch 49/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9826 - loss: 0.0536
Epoch 50/50
5767/5767 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.9827 - loss: 0.0529

In [54]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

1923/1923 - 1s - 652us/step - accuracy: 0.9328 - loss: 0.2752
Loss: 0.27524620294570923, Accuracy: 0.9327545166015625

In [56]:
# Exporting our model to HDF5 file

# Defining the filename for saving the model
filename = 'Heart_disease_model.h5'  

# Exporting the model to HDF5 file
nn_model.save(filename)

print(f"Model saved to {filename}")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model saved to Heart_disease_model.h5